#!/usr/bin/env perl

# Self disable on rpm distro
use OSCAR::Logger;
use OSCAR::LoggerDefs;
use OSCAR::OCA::OS_Detect;
use OSCAR::ODA_Defs;
use OSCAR::Database;
my $os = OSCAR::OCA::OS_Detect::open();
my %selection_data = (); 
if ($os->{pkg} eq "rpm") {
    oscar_log(2, INFO, "RPM based distro: rapt opkg self unselect");
    $selection_data{'rapt'} = OSCAR::ODA_Defs::UNSELECTED();
    if(OSCAR::Database::set_opkgs_selection_data (%selection_data)) {
        exit 0;
    } else {
        oscar_log(1, ERROR, "Failed to unselect rapt opkg on rpm based distro.");
	exit 1;
    }
}
